### ISSUE TITLE
script to work with MFA enabled orgs

### ISSUE THREAD

**Issue by divya-achan** [ssvaidyanathan/apigee-trireme-finder#1]
The script should also run for apigee orgs that are MFA enabled.

**Comment by ssvaidyanathan** [comment]
@divya-achan - I have made the necessary changes. Please delete your node_modules and run `npm install` again to download new dependencies. The new changes now should prompt if you want to use Basic Auth or OAuth. If Basic, you need to provide username and password. If OAuth, you need to provide the Token 

Let me know if it works and reopen this issue if you see any problem
