### ISSUE TITLE
Unhandled Promisse Rejection. 

### ISSUE THREAD

**Issue by Gabriel-Pellegrini** [ssvaidyanathan/apigee-trireme-finder#2]
I'm facing an error when I try to check each proxy revision. 
I'm not sure if it's an issue or it's an error on my local repo. 

>   Fetching all proxies in leroymerlinbrasil org...
Fetch complete
Checking each proxy revision...
(node:14621) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: revisions is not iterable
(node:14621) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 

Could you help me with this problem?

Thank you.

**Comment by ssvaidyanathan** [comment]
Hi @Gabriel-Pellegrini 
Not sure why that is coming. Can you add the following line after line 100 in *trireme_proxy_finder.js*
```console.log("api: " + api);```
so that we know which Proxy is throwing this error

**Comment by Gabriel-Pellegrini** [comment]
I made the change and got the following:

> Checking each proxy revision...
api: <
>
I believe it's not recognizing the proxy, would be it?

**Comment by ssvaidyanathan** [comment]
@Gabriel-Pellegrini - can you please check if you are using Node.js version >=8
I tried and it is working for me. If you change your Node.js version, please delete the node_modules directory and run `npm install` again before running the command

**Comment by Gabriel-Pellegrini** [comment]
@ssvaidyanathan  I checked and I'm using node version 8.7.0 
It's weird because I also tried with node v8.11.2 and got the same error. 

Do you have an example of how it should works? I noticed that I must have the appropriated allows to get the Proxies properties, What specific permission the user should have to get the api proxy information ?

**Comment by ssvaidyanathan** [comment]
Org admin should be fine. I have v10.16.0 on my machine. I was able to run it. Let me try it with 8.7.0 and see if I can replicate. Can you try with >=v10

**Comment by ssvaidyanathan** [comment]
I just checked with v8.7.0 and it works for me. I got temp access to your org and tried the script pointing to your org using v10.16.0 and v8.7.0. Both gave me output without any error. I can email the output to you if you want.

**Comment by Gabriel-Pellegrini** [comment]
I'll try with >=v10 

Could you email the output to gpellegrini@leroymerlin.com.br ? 
Thank you very much.

**Comment by Gabriel-Pellegrini** [comment]
I changed the Management Host, and it worked.
Thank you for your support.

**Comment by ssvaidyanathan** [comment]
awesome ! I knew folks could have issues with that, so I included the default Management host in the script.
